/// Flutter icons CrownApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CrownApp
///      fonts:
///       - asset: fonts/CrownApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CrownApp {
  CrownApp._();

  static const _kFontFam = 'CrownApp';
  static const _kFontPkg = null;

  static const IconData ic_font_death = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_font_mask = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_font_recovered = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
