/// Flutter icons CrownApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CrownApp
///      fonts:
///       - asset: fonts/CrownApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CrownApp {
  CrownApp._();

  static const _kFontFam = 'CrownApp';

  static const IconData iconfinder_emoji_emoticon_35_3638429 = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData iconfinder_recovered_immune_strong_healthy_revive_5969421 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData iconfinder_disease_29_5766041 = IconData(0xe802, fontFamily: _kFontFam);
}
